baseURL = "https://piko-heksagon.netlify.app/"
languageCode = "en-us"
title = " MordiJC's blog"
theme = "piko"
paginate = "9"
copyright = 'A template by [Heksagon](https://www.heksagon.net "Your most friendly developer")'
enableRobotsTXT = true
buildDrafts = true
buildFuture = true
buildExpired = false
enableEmoji = true

[outputs]
home = [ "HTML", "RSS", "JSON" ]

[minify]
disableCSS = false
disableHTML = false
disableJS = false
disableJSON = false
disableSVG = false
disableXML = false
minifyOutput = true

[minify.tdewolff.html]
keepWhitespace = false

[params]
env = "production"
author = "Jakub Czapiga"
description = "Firmware, software and sometimes hardware tips."
math = false
images = [ "/uploads/og.webp" ]
comments = true
mainSections = [ "blog" ]
ShowShareButtons = true
ShowCodeCopyButtons = true
ShowRelated = true
# CookieNotice = "We use cookies to improve your experience on our site."
# CookieLink = "/legal/privacy/#cookies-and-web-beacons"
# CookieButton = "Cookies Policy"
disableAnchoredHeadings = false
ShowReadingTime = true
ShowBreadCrumbs = true

[params.analytics.google]
# SiteVerificationTag =

[params.analytics.yandex]
# SiteVerificationTag =

[params.analytics.bing]
# SiteVerificationTag =

[params.label]
title = "_MordiJC's blog_"
text = ""
lightNavIcon = "/uploads/hex_logo_simple_red.svg"
darkNavIcon = "/uploads/hex_logo_simple_gold.svg"
iconHeight = "35"
iconWIdth = "35"

[params.assets]
disableFingerprinting = false
favicon = "/uploads/hex_logo_simple_gold.svg"
favicon16x16 = "/uploads/hex_logo_simple_gold.svg"
favicon32x32 = "/uploads/hex_logo_simple_gold.svg"
apple_touch_icon = "/uploads/hex_logo_simple_gold.svg"
safari_pinned_tab = "/uploads/hex_logo_simple_gold.svg"

[params.homepage]
disableHeroSection = false
heroTitle = "Piko"
heroDescription = "Lightweight theme for your every need"
heroCTAPrimaryText = "Blog"
heroCTAPrimaryUrl = "/blog/"
heroCTASecondaryText = "Contact Me"
heroCTASecondaryUrl = "/contact/"
heroBackgroundImage = "/uploads/portfolio-1.webp"
disableBlogSection = false
blogTitle = "Latest Posts"
blogDescription = "This is my latest blog posts"
seeMoreText = "More Posts"
disableAboutSection = false
aboutTitle = "About"
aboutDescription = "Just something about me"
aboutImgUrl = "/uploads/self.webp"
aboutContent = "Hi guys. This is where you put something about yourself."
disablePortfolioSection = false
portfolioTitle = "Portfolio"
portfolioDescription = "Some of my works"

[[params.homepage.portfolio]]
imageUrl = "/uploads/portfolio-1.webp"
description = "Portfolio One."

[[params.homepage.portfolio]]
imageUrl = "/uploads/portfolio-2.webp"
description = "Portfolio Two."

[[params.homepage.portfolio]]
imageUrl = "/uploads/portfolio-3.webp"
description = "Portfolio Three."

[params.fuseOpts]
isCaseSensitive = false
shouldSort = true
location = "0"
distance = "1000"
threshold = "0.4"
minMatchCharLength = "0"
keys = [ "title", "permalink", "summary", "content" ]

[[params.plugins.css]]
link = "plugins/css/pico.min.css"

[[params.plugins.js]]
link = "plugins/js/feather.min.js"

[[menus.main]]
name = "Blog"
title = "Blog"
pre = "pen-tool"
url = "/blog"
weight = "20"

[[menus.main]]
name = "Search"
title = "Search"
pre = "search"
url = "/search"
weight = "30"

# [[menus.main]]
# name = "Contact"
# title = "Contact"
# pre = "mail"
# url = "/contact"
# weight = "40"

[[menus.main]]
name = "Github"
pre = "github"
url = "https://github.com/mordijc"
weight = "50"

[[menus.search]]
name = "Categories"
title = "Categories"
url = "/categories"
weight = "10"

[[menus.search]]
name = "Archives"
title = "Archives"
url = "/archives"
weight = "20"

[[menus.search]]
name = "Tags"
title = "Tags"
url = "/tags"
weight = "30"

